language: python

python:
  - "3.6"

before_install: pip install pipenv

install:
  - pipenv install --dev
  - pip install coveralls
  - pip install -e .

script: pipenv run pytest

after_success: coveralls

deploy:
  provider: script
  script: ./resin-deploy.sh
  on:
    tags: true
