dist: xenial

language: python

python:
  - "3.7"

branches:
  except:
    # Exclude dependabot branches push build
    # Build is already triggered by PR
    - /^dependabot\/.*$/

before_install:
  - pip install --upgrade pip
  - >
    curl -sSL -o /tmp/get-poetry.py
    https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python /tmp/get-poetry.py -y
  - source $HOME/.poetry/env

install:
  - poetry install
  - pip install pre-commit

script:
  - pre-commit run --all-files
  - poetry run pytest --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: ./balena-deploy.sh
