language: python

python:
  - "3.6"

branches:
  except:
    # Exclude dependabot branches push build
    # Build is already triggered by PR
    - /^dependabot\/.*$/

before_install: pip install pipenv

install:
  - pipenv install --dev
  - pip install coveralls

script: pipenv run pytest --verbose

after_success: coveralls

deploy:
  provider: script
  script: ./resin-deploy.sh
