language: python

python:
  - "3.7"

branches:
  except:
    # Exclude dependabot branches push build
    # Build is already triggered by PR
    - /^dependabot\/.*$/

install:
  - pip install --upgrade pip
  - >
    curl -sSL -o /tmp/get-poetry.py
    https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python /tmp/get-poetry.py -y
  - source $HOME/.poetry/env
  - poetry install
  - pip install coveralls

script: poetry run pytest --verbose

after_success: coveralls

deploy:
  provider: script
  script: ./balena-deploy.sh
