# Dockerfile for running pilotwire-controller daemon with resin.io
FROM resin/%%RESIN_MACHINE_NAME%%-alpine-python:3.6

WORKDIR /usr/src/app

COPY Pipfile Pipfile.lock ./

RUN set -ex \
    && pip install --upgrade pipenv \
    && pipenv install --deploy --system

COPY pilotwire_controller ./pilotwire_controller

RUN python -m compileall pilotwire_controller

ENV INITSYSTEM on

ENV FLASK_APP pilotwire_controller/api.py

CMD [ "flask", "run", "--host=0.0.0.0" ]
